baseURL = "/"
title = "灏天阁"
author = "hao"
copyright = "Copyright © 2008–2019, Steve Francia and the lee.so; all rights reserved."
paginate = 3
languageCode = "zh"
DefaultContentLanguage = "zh"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
theme = "paper"

[params]
  color = 'white'
  twitter = 'yinchuanbo'
  github = 'yinchuanbo'
  instagram = 'yinchuanbo'
  rss = true
  avatar = 'https://yinchuanbo.github.io/imgs/avator.jpg'
  name = '灏 Yin'
  bio = '学而不知道，与不学同；知而不能行，与不知同。'
  disableHLJS = true
  monoDarkIcon = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true